### ISSUE TITLE
Ohmic heating definition incorrect

### ISSUE THREAD

**Issue by bclyons12** [ProjectTorreyPines/IMAS.jl#198]
I believe the definition of the ohmic heating source is incorrect here (and maybe elsewhere?): https://github.com/ProjectTorreyPines/IMAS.jl/blob/a01ca5633bc5d90ad49c6a4cf68e2c5b255751a9/src/physics/sources.jl#L44-L59

Ohmic heating power density should be proportional to `J * J_OH` not `J_OH^2`. As shown below, this works out to `Q_OH = eta * <Jt/R> * <J_OH . B> / (F <R^-2>)`, so it should be (with appropriate interpolating, as done in `Jpar_2_Jtor()` and such:
```
Q_OH = (cp1d.j_tor * eq1d.gm9) * (cp1d.j_ohmic * B0) / (eq1d.f * eq1d.gm1 * cp1d.conductivity_parallel)
```

### Details
From the ONETWO notes, based on Hinton & Hazeltine:
![Screenshot 2024-09-20 at 1 31 02 PM](https://github.com/user-attachments/assets/9bb80552-dd82-4669-a617-ff156af7a185)
Intuitively, the Ohmic heating should come from the loss in poloidal magnetic energy, which is proportional to B^2, so (B_NI + B_OH)^2 has the cross term that needs to be accounted for.

Making @jmcclena aware, who agrees our current definition is wrong.

**Comment by orso82** [comment]
@bclyons12 please double check

**Comment by bclyons12** [comment]
Regarding f348dae58f5a8b7a2fa0331bbe79080c7c8148d5, is `eqt.global_quantities.vacuum_toroidal_field.b0` correct, or should we do something like `B0 = get_time_array(eq.vacuum_toroidal_field, :b0, eqt.time, :constant)` as in `Jpar_2_Jtor()`?

Otherwise it looks right to me. Can we benchmark it agains ohmic heating calculations from TGYRO, ONETWO, TRANSP, etc.?

**Comment by orso82** [comment]
@bclyons12 the two are equivalent

**Comment by orso82** [comment]
we can use TRANSP or ONETWO to benchmark. TGYRO just takes the sources from these
